--- #YAML:1.0
name:               namespace-clean
version:            0.20_01
abstract:           Keep imports and functions out of your namespace
author:
    - Robert 'phaylon' Sedlacek <rs@474.at>, Florian Ragwitz <rafl@debian.org>, Jesse Luehrs <doy@tozt.net>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    Test::More:  0.88
requires:
    B::Hooks::EndOfScope:  0.07
    Package::Stash:       0.23
resources:
    bugtracker:  http://rt.cpan.org/Public/Dist/Display.html?Name=namespace-clean
    homepage:    http://search.cpan.org/dist/namespace-clean
    repository:  git://git.shadowcat.co.uk:p5sagit/namespace-clean.git
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
