abstract: Keep imports out of your namespace
author: Robert 'phaylon' Sedlacek <rs@474.at>
build_requires: 
  FindBin: 0
  Test::More: 0.62
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: namespace-clean
no_index: 
  directory: 
    - inc
    - t
requires: 
  Filter::EOF: 0.02
  Symbol: 0
version: 0.02
