---
abstract: 'Keep imports and functions out of your namespace'
author:
  - "Robert 'phaylon' Sedlacek <rs@474.at>"
  - 'Florian Ragwitz <rafl@debian.org>'
  - 'Jesse Luehrs <doy@tozt.net>'
build_requires:
  Exporter: 0
  FindBin: 0
  Test::More: 0.88
  constant: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.101612, CPAN::Meta::Converter version 2.101600'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: namespace-clean
requires:
  B::Hooks::EndOfScope: 0.07
  Package::Stash: 0.03
  Sub::Identify: 0.04
  Sub::Name: 0.04
  vars: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=namespace-clean
  homepage: http://search.cpan.org/dist/namespace-clean
  repository: git://github.com/rafl/namespace-clean.git
version: 0.18
x_Dist_Zilla:
  plugins:
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@FLORA/@Basic/GatherDir'
      version: 4.101612
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@FLORA/@Basic/PruneCruft'
      version: 4.101612
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@FLORA/@Basic/ManifestSkip'
      version: 4.101612
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@FLORA/@Basic/MetaYAML'
      version: 4.101612
    -
      class: Dist::Zilla::Plugin::License
      name: '@FLORA/@Basic/License'
      version: 4.101612
    -
      class: Dist::Zilla::Plugin::Readme
      name: '@FLORA/@Basic/Readme'
      version: 4.101612
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@FLORA/@Basic/ExtraTests'
      version: 4.101612
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@FLORA/@Basic/ExecDir'
      version: 4.101612
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@FLORA/@Basic/ShareDir'
      version: 4.101612
    -
      class: Dist::Zilla::Plugin::MakeMaker
      name: '@FLORA/@Basic/MakeMaker'
      version: 4.101612
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@FLORA/@Basic/Manifest'
      version: 4.101612
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@FLORA/@Basic/TestRelease'
      version: 4.101612
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@FLORA/@Basic/ConfirmRelease'
      version: 4.101612
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@FLORA/@Basic/UploadToCPAN'
      version: 4.101612
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@FLORA/MetaConfig'
      version: 4.101612
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@FLORA/MetaJSON'
      version: 4.101612
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: '@FLORA/PkgVersion'
      version: 4.101612
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@FLORA/PodSyntaxTests'
      version: 4.101612
    -
      class: Dist::Zilla::Plugin::NoTabsTests
      name: '@FLORA/NoTabsTests'
      version: 0.01
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: '@FLORA/PodCoverageTests'
      version: 4.101612
    -
      class: Dist::Zilla::Plugin::MetaResources
      name: '@FLORA/MetaResources'
      version: 4.101612
    -
      class: Dist::Zilla::Plugin::Authority
      name: '@FLORA/Authority'
      version: 1.000
    -
      class: Dist::Zilla::Plugin::EOLTests
      name: '@FLORA/EOLTests'
      version: 0.02
    -
      class: Dist::Zilla::Plugin::PodWeaver
      name: '@FLORA/PodWeaver'
      version: 3.101530
    -
      class: Dist::Zilla::Plugin::AutoPrereq
      name: AutoPrereq
      version: 4.101612
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.101612
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.101612
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.101612
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.101612
  zilla:
    class: Dist::Zilla
    config:
      is_trial: 0
    version: 4.101612
x_authority: cpan:PHAYLON
